defaults:
  - agent: PPO
  - _self_

name: christiano


kwargs:
  n_ensembles_rew: 3
  lr_rew: 3e-4
  batch_size_rew: 32
  n_ephochs_rew: 10
  n_iterations: 10
  train_comparison_frac: 0.1
  fragment_length: 25
  transition_oversampling: 1.0
  initial_comparison_frac: 0.1
  initial_epoch_multiplier: 200.0
  query_schedule: "hyperbolic"
  comparison_queue_size: null


train:
  kwargs:
    total_timesteps: 100000
    total_comparisons: 1000