name: humlrn-v0
expert_id: ppo-v0


kwargs:
  # reward model
  n_ensembles: 5
  segment_length: 25
  device: cpu
  lr_reward_model: 1e-5
  max_dataset_size: 10000
  reward_model_batch_size: 32
  reward_training_epochs: 5
  # preference schedule
  num_pairs_initial: 250
  num_pairs_final: 0
  decay_pairs_schedule: 1.0
  # demonstrations
  use_demonstrations: false
  num_demo_episodes_per_iter: 10
  lambda_demo: 1.0
  demo_margin: 1.0


train:
  kwargs:
    total_timesteps: 5e5
    num_iterations: 20


agent:
  algo: "PPO"
  kwargs:
    policy: "MlpPolicy"
    learning_rate: 3e-4
    n_steps: 1024
    batch_size: 256
    n_epochs: 5
    gamma: 0.995
    gae_lambda: 0.95
    clip_range: 0.2
    clip_range_vf: null
    normalize_advantage: true
    ent_coef: 0.03
    vf_coef: 0.8
    max_grad_norm: 0.5
    use_sde: false
    sde_sample_freq: -1
    rollout_buffer_class: null
    rollout_buffer_kwargs: {}
    target_kl: null
    stats_window_size: 100
    policy_kwargs:
      net_arch: [256, 128]
    seed: ${run.seed}
    device: "cpu"
    tensorboard_log: ${hydra:runtime.cwd}/tensorboard
    verbose: 1

