

run:
  seed: 0
  output_dir: "./outputs"
  baseline: false

env:
  id: "HighwayEgo-v0"
  n_envs: 4
  kwargs:
    ego: "continuous"
    reward: "fast"

agent:
  kwargs:
    policy: "MlpPolicy"
    n_steps: 1000
    n_epochs: 10
    learning_rate: 0.0003
    batch_size: 64
    ent_coef: 0.01
    gae_lambda: 0.95
    gamma: 0.995
    policy_kwargs:
      net_arch: [64, 64]
    device: "cpu"
    seed: 0

algo:
  kwargs:
    lr_rew: 0.0003
    n_epochs_rew: 1
    batch_size_rew: 1000
    l2_rew: 0.0001
    fragment_length: 1
    transition_oversampling: 1
    initial_comparisons: 500
    initial_epoch_multiplier: 1
    comparison_queue_size: 1000000
    n_ensembles_rew: 3
    train_comparison_frac: 0.8
    net_arch_rew: [128, 128]
    fragmenter_type: active

train:
  kwargs:
    total_timesteps: 1000000
    comparisons_per_iteration: 2000
    comparison_timesteps_per_iteration: 20000
    timesteps_per_iteration: 20000
    checkpoint_interval: 10

hydra:
  job:
    chdir: false
  run:
    dir: ${run.output_dir}/${now:%Y-%m-%d_%H-%M-%S}
