
run:
  seed: 0
  output_dir: Null

wandb:
  entity: Null
  project: Null
  tags: Null

env:
  id: "HighwayEgo-v0"
  n_envs: 4
  kwargs:
    ego: "continuous"
    reward: "fast"

agent:
  kwargs:
    policy: "MlpPolicy"
    n_steps: 1000
    n_epochs: 10
    learning_rate: 0.0003
    batch_size: 64
    ent_coef: 0.01
    gae_lambda: 0.95
    gamma: 0.997
    policy_kwargs:
      net_arch: [64, 64]
    device: "cpu"

algo:
  kwargs:
    lr_rew: 0.001
    gradient_steps_rew: 100
    batch_size_expert: 32
    batch_size_model: 64
    l2_rew: 0.01
    fragment_length: 1
    temperature: 1.0
    initial_queries: 100
    exploration_frac: 0.0
    exploration_eps: 0.5
    query_schedule: "constant"
    grad_clip_rew: null
    reward_model_kwargs:
      n_ensembles: 3
      net_arch: [32, 32]
      activation_fn: tanh

train:
  kwargs:
    total_timesteps: 4000000
    total_queries: 10000
    timesteps_per_iteration: 20000
    checkpoint_interval: 10

hydra:
  job:
    chdir: false
  run:
    dir: .
  output_subdir: null
