
run:
  seed: 0
  output_dir: Null
  baseline: false

wandb: 
  entity: Null
  project: Null
  tags: Null


env:
  id: "HighwayEgo-v0"
  n_envs: 4
  kwargs:
    ego: "continuous"
    reward: "fast"

agent:
  kwargs:
    policy: "MlpPolicy"
    n_steps: 1000
    n_epochs: 10
    learning_rate: 0.0003
    batch_size: 100
    ent_coef: 0.01
    gae_lambda: 0.95
    gamma: 0.995
    policy_kwargs:
      net_arch: [64, 64]
    device: "cpu"

algo:
  kwargs:
    lr_rew: 0.0003
    gradient_steps_rew: 30
    batch_size_rew: 128
    l2_rew: 0.0001
    bt_temperature: 1.0
    fragment_length: 1
    initial_queries: 500
    exploration_frac: 0.0
    exploration_eps: 0.5
    hard_labels: True
    query_schedule: "constant"
    comparison_queue_size: 1000000
    train_comparison_frac: 0.8
    fragmenter_type: active
    pessimism: 0.0
    reward_model_kwargs:
      n_ensembles: 1
      net_arch: [128, 128]
      activation_fn: tanh

train:
  kwargs:
    total_timesteps: 1000000
    total_queries: 100000
    timesteps_per_iteration: 20000
    checkpoint_dir: Null
    checkpoint_interval: 10

hydra:
  job:
    chdir: false
  run:
    dir: .
  output_subdir: null
